spring:
  application:
    name: configCenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jrlygdsj/Test001
          username: 815545265@qq.com
          password: 123456.com~!@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
